# Programming Assignment 5
---
**Author:** Garrett Ward 
**Version:** 1.0  
**Semester:** Spring 2024 

This *notebook* contains my solution(s) to **Programming Assignment 5**

### Problem 1 - Language Translator

In [2]:
translation_dictionary = {
    'apple': 'Apfel',
    'banana': 'Banane',
    'car': 'Auto',
    'house': 'Haus',
    'sun': 'Sonne',
    'moon': 'Mond',
    'water': 'Wasser',
    'fire': 'Feuer',
    'tree': 'Baum',
    'mountain': 'Berg',
    'cat': 'Katze',
    'dog': 'Hund',
    'book': 'Buch',
    'computer': 'Computer',
    'phone': 'Telefon',
    'flower': 'Blume',
    'friend': 'Freund',
    'love': 'Liebe',
    'happy': 'glücklich',
    'sad': 'traurig',
}

def translate_word(word):
    if word.lower() in translation_dictionary:
        translated_word = translation_dictionary[word.lower()]
        print(f"The German word for {word} is {translated_word}.")
    else:
        print(f"The German translation for {word} is not available.")

def main():
    print("Enter a word in English to translate it to German. Or enter 'Q' to quit.")

    while True:
        word = input("Enter an English word (or 'Q' to quit): ")
        if word.lower() == 'q':
            break
        translate_word(word)

if __name__ == "__main__":
    main()

Enter a word in English to translate it to German. Or enter 'Q' to quit.


Enter an English word (or 'Q' to quit):  Sad


The German word for Sad is traurig.


Enter an English word (or 'Q' to quit):  Flower


The German word for Flower is Blume.


Enter an English word (or 'Q' to quit):  Love


The German word for Love is Liebe.


Enter an English word (or 'Q' to quit):  


The German translation for  is not available.


Enter an English word (or 'Q' to quit):  Q


### Problem 2 - Translating Morse Code

In [5]:
morse_code_dictionary = {
    'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....', 'I': '..', 'J': '.---',
    'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 'Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-',
    'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-', 'Y': '-.--', 'Z': '--..',
    '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....',
    '6': '-....', '7': '--...', '8': '---..', '9': '----.',
}

def translate_to_morse(sentence):
    morse_code_translation = ""
    for char in sentence:
        if char.upper() in morse_code_dictionary:
            morse_code_translation += morse_code_dictionary[char.upper()] + " "
    return morse_code_translation.strip()

def main():
    print("Enter a sentence to translate to Morse Code.Or enter 'q' to quit.")

    while True:
        message = input("Enter a sentence (or 'q' to quit): ")
        if message.lower() == 'q':
            break
        morse_code = translate_to_morse(message)
        print("Morse Code Translation:", morse_code)

if __name__ == "__main__":
    main()

Enter a sentence to translate to Morse Code.Or enter 'q' to quit.


Enter a sentence (or 'q' to quit):  Hello world


Morse Code Translation: .... . .-.. .-.. --- .-- --- .-. .-.. -..


Enter a sentence (or 'q' to quit):  S O S


Morse Code Translation: ... --- ...


Enter a sentence (or 'q' to quit):  q


### Problem 3 - Comparing Minors/Majors

In [31]:
cs_minor = {"CS100", "CS101", "CS131", "CS215", "CS233", "CS330","CS400", "MATH120"} 
buisness_admin_minor = {"BUSA103","BUSA203", "BUSA301", "BUSA305", "ACCT101", "ECON110", "FINA315", "MATH125", "MATH117"}
business_analytics_minor = {"BUSA103", "BUSA245", "BUSA346", "CS150", "DS160", "DS300"}
ds_minor = {"BUSA103", "BUSA245", "BUSA346", "CS150", "DS160", "DS300", "DS450", "MATH205", "MATH215", "MATH430", "ECON410", "ECON322", "ECON351", "DS444"} 

business_admin_and_analytics_overlap = buisness_admin_minor.intersection(business_analytics_minor)
print(f" i. If a student minors in Business Administration and Business Analytics the courses that overlap are:{business_admin_and_analytics_overlap}.")

all_buisness_admin_and_cs_classes = buisness_admin_minor.union(cs_minor)
print(f" ii. If a student minors in Business Administration and Computer Science they will have to take all of the following courses:{all_buisness_admin_and_cs_classes}.")

business_admin_not_in_analytics = buisness_admin_minor.difference(business_analytics_minor)
print(f" iii. Courses required to minor in Business Administration but not Business Analytics:{business_admin_not_in_analytics}.")

cs_and_ds_overlap = cs_minor.intersection(ds_minor)
print(f" iv. The overlapping courses for a minor in Computer Science and Data Science are: {cs_and_ds_overlap if cs_and_ds_overlap else 'None'}")

busa_analytics_in_ds = business_analytics_minor.issubset(ds_minor)
print(f" v. Is Business Analytics completely subsumed by Data Science? {'Yes' if busa_analytics_in_ds else 'No'}")

 i. If a student minors in Business Administration and Business Analytics the courses that overlap are:{'BUSA103'}.
 ii. If a student minors in Business Administration and Computer Science they will have to take all of the following courses:{'CS131', 'MATH120', 'CS400', 'BUSA301', 'MATH125', 'BUSA103', 'FINA315', 'CS215', 'ECON110', 'CS101', 'CS233', 'BUSA305', 'BUSA203', 'MATH117', 'CS100', 'CS330', 'ACCT101'}.
 iii. Courses required to minor in Business Administration but not Business Analytics:{'ACCT101', 'BUSA301', 'MATH125', 'FINA315', 'BUSA305', 'BUSA203', 'MATH117', 'ECON110'}.
 iv. The overlapping courses for a minor in Computer Science and Data Science are: None
 v. Is Business Analytics completely subsumed by Data Science? Yes


### Problem 4 - Working with NumPy

In [17]:
import numpy as np

array1 = np.random.randint(0, 21, size=(5, 5))
array2 = np.random.randint(0, 21, size=(5, 5))

print("Array 1:")
print(array1)
print("\n Array 2:")
print(array2)

maxtrix_product = np.matmul(array1,array2)
print("\n Matrix Product:")
print(matrix_product)

dot_product = np.dot(array1.flatten(), array2.flatten())
print("\n Dot Product:")
print(dot_product)

det_array1 = np.linalg.det(array1)
det_array2 = np.linalg.det(array2)

print("\nDeterminant of Array 1:")
print(det_array1)
print("\nDeterminant of Array 2:")
print(det_array2)

if det_array1 != 0:
    inv_array1 = np.linalg.inv(array1)
    print("\nInverse of Array 1:")
    print(inv_array1)
else:
    print("\nArray 1 is not invertible.")
    
if det_array2 != 0:
    inv_array2 = np.linalg.inv(array2)
    print("\nInverse of Array 2:")
    print(inv_array2)
else: 
    print("\nArray2 is not invertible.")
          
array3 = np.linspace(0,1,20)
array4 = np.linspace(1,2,20)
combined_array = np.concatenate((array3,array4))
          
reshaped_array = combined_array.reshape(10,4)
          
print("\nReshaped Combined Array:")
print(reshaped_array)

Array 1:
[[17  2  5  9  4]
 [ 8 10 10 17  6]
 [ 4 16  5 15 10]
 [19  1  8  2 15]
 [ 1 12  3  9 10]]

 Array 2:
[[11 13  7  6  2]
 [16 12  6 13  9]
 [11 13  6 10 19]
 [19  7  9 17  6]
 [14 10 14 14 20]]

 Matrix Product:
[[384 454 574 160 756]
 [550 557 755 317 952]
 [282 231 431 124 655]
 [489 345 531 339 608]
 [381 220 460 240 639]]

 Dot Product:
2581

Determinant of Array 1:
18651.999999999993

Determinant of Array 2:
-812.0000000000317

Inverse of Array 1:
[[-0.01372507 -0.09092859  0.29830581  0.05747373 -0.32446923]
 [-0.28634999 -0.17831868  0.9541068   0.18346558 -1.00777397]
 [-0.32093073  0.06133391  0.52991636  0.18764744 -0.71981557]
 [ 0.30473944  0.14389878 -0.79519623 -0.2135964   0.90735578]
 [ 0.16700622  0.0751662  -0.61805704 -0.08996354  0.74110015]]

Inverse of Array 2:
[[  6.31527094 -25.72413793  15.97044335  15.31280788  -8.82142857]
 [ -2.38916256  10.03448276  -6.18226601  -5.98768473   3.39285714]
 [ -0.20689655   1.06896552  -0.79310345  -0.68965517   0.5   